package com.example.core.trialengine.policy

import com.example.core.evolutionengine.catalog.ClassCatalog
import com.example.core.trialengine.model.TrialCategory
import com.example.core.trialengine.model.TrialPolicy
import com.example.core.trialengine.model.TrialScoringMethod

/**
 * PERFORMAI TRIAL POLICY REGISTRY
 *
 * Registrador imutável e versionado de Políticas de Trial.
 * NENHUM threshold arbitrário ou fictício é introduzido.
 * Parâmetros não homologados permanecem rigorosamente com thresholdValue = null e methodologyStatus = "PENDING_VALIDATION".
 */
object TrialPolicyRegistry {

    private val policies = mapOf(
        ClassCatalog.CLASS_08 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-08-V1",
            classId = ClassCatalog.CLASS_08,
            version = "1.0.0",
            name = "Prova de Capacidade de Carga Inicial",
            description = "Avaliação padronizada de prontidão neuromuscular e tolerância mecânica controlada.",
            category = TrialCategory.NEUROMUSCULAR,
            requiredEvidenceTypes = listOf("DIRECT_SENSOR_BIOMECHANICAL", "MOTION_CAPTURE_STANDARDIZED"),
            protocolId = "PROT-TRIAL-LOAD-01",
            allowedDevices = listOf("LAB_FORCE_PLATE_V1", "CALIBRATED_LINEAR_TRANSDUCER_V1", "PERFORMAI_OPTICAL_RIG_V1"),
            minimumAttempts = 2,
            maximumAttempts = 3,
            restPeriodSeconds = 180,
            executionWindowSeconds = 3600,
            validityWindowDays = 90,
            safetyRequirements = listOf("SUPERVISION_REQUIRED", "WARMUP_CONFIRMED", "EMERGENCY_STOP_AVAILABLE"),
            scoringMethod = TrialScoringMethod.BEST_ATTEMPT,
            thresholdValue = null, // Não inventado
            thresholdUnit = "N/kg",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_10 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-10-V1",
            classId = ClassCatalog.CLASS_10,
            version = "1.0.0",
            name = "Prova de Potência Mecânica do Atleta",
            description = "Teste de produção de potência neuromuscular explosiva em plataforma de força.",
            category = TrialCategory.POWER_ENDURANCE,
            requiredEvidenceTypes = listOf("DIRECT_SENSOR_FORCE_PLATE", "TIME_SERIES_TELEMETRY"),
            protocolId = "PROT-TRIAL-POWER-01",
            allowedDevices = listOf("LAB_FORCE_PLATE_V1", "VALIDATED_ENCODER_V1"),
            minimumAttempts = 2,
            maximumAttempts = 3,
            restPeriodSeconds = 240,
            executionWindowSeconds = 3600,
            validityWindowDays = 90,
            safetyRequirements = listOf("SUPERVISION_REQUIRED", "SYSTEM_CALIBRATED"),
            scoringMethod = TrialScoringMethod.BEST_ATTEMPT,
            thresholdValue = null,
            thresholdUnit = "W/kg",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_12 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-12-V1",
            classId = ClassCatalog.CLASS_12,
            version = "1.0.0",
            name = "Prova de Produção Rápida de Força",
            description = "Avaliação de taxa de desenvolvimento de força (RFD) e rigidez mecânica.",
            category = TrialCategory.NEUROMUSCULAR,
            requiredEvidenceTypes = listOf("HIGH_FREQUENCY_FORCE_TIME", "KINEMATIC_VECTOR_SERIES"),
            protocolId = "PROT-TRIAL-RFD-01",
            allowedDevices = listOf("LAB_FORCE_PLATE_V1", "DUAL_AXIS_ISOKINETIC_V1"),
            minimumAttempts = 3,
            maximumAttempts = 3,
            restPeriodSeconds = 300,
            executionWindowSeconds = 3600,
            validityWindowDays = 90,
            safetyRequirements = listOf("SPECIALIST_PRESENT", "JOINT_INTEGRITY_CHECK"),
            scoringMethod = TrialScoringMethod.MEAN_ATTEMPTS,
            thresholdValue = null,
            thresholdUnit = "N/s",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_14 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-14-V1",
            classId = ClassCatalog.CLASS_14,
            version = "1.0.0",
            name = "Prova de Resistência Neuromuscular Sob Alta Carga",
            description = "Série controlada de repetições padronizadas com mensuração de perda de velocidade.",
            category = TrialCategory.POWER_ENDURANCE,
            requiredEvidenceTypes = listOf("LINEAR_VELOCITY_LOSS_ARRAY", "FORCE_PLATE_GROUND_REACTION"),
            protocolId = "PROT-TRIAL-VELOCITY-LOSS-01",
            allowedDevices = listOf("LAB_FORCE_PLATE_V1", "CALIBRATED_LINEAR_TRANSDUCER_V1"),
            minimumAttempts = 1,
            maximumAttempts = 2,
            restPeriodSeconds = 360,
            executionWindowSeconds = 3600,
            validityWindowDays = 60,
            safetyRequirements = listOf("SAFETY_SPOTTERS_2X", "BARBELL_CATCH_DEPLOYED"),
            scoringMethod = TrialScoringMethod.BEST_ATTEMPT,
            thresholdValue = null,
            thresholdUnit = "VELOCITY_PERCENT_DROP",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_15 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-15-V1",
            classId = ClassCatalog.CLASS_15,
            version = "1.0.0",
            name = "Prova de Excelência Competitiva",
            description = "Bateria de avaliação combinada de força isométrica máxima e potência dinâmica.",
            category = TrialCategory.MAXIMUM_STRENGTH,
            requiredEvidenceTypes = listOf("MULTI_AXIS_IMTP_SERIES", "3D_MOTION_CAPTURE_ARRAY"),
            protocolId = "PROT-TRIAL-ELITE-IMTP-01",
            allowedDevices = listOf("LAB_FORCE_PLATE_V1", "GOLD_STANDARD_ISOMETRIC_RIG_V1"),
            minimumAttempts = 3,
            maximumAttempts = 3,
            restPeriodSeconds = 300,
            executionWindowSeconds = 3600,
            validityWindowDays = 60,
            safetyRequirements = listOf("CERTIFIED_LABORATORY", "MEDICAL_CLEARANCE_ACTIVE"),
            scoringMethod = TrialScoringMethod.BEST_ATTEMPT,
            thresholdValue = null,
            thresholdUnit = "N",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_16 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-16-V1",
            classId = ClassCatalog.CLASS_16,
            version = "1.0.0",
            name = "Prova de Força Isométrica Absoluta de Elite",
            description = "Tracionamento isométrico em meia coxa (IMTP) com rigor laboratorial.",
            category = TrialCategory.MAXIMUM_STRENGTH,
            requiredEvidenceTypes = listOf("MULTI_AXIS_IMTP_SERIES"),
            protocolId = "PROT-TRIAL-TITAN-IMTP-01",
            allowedDevices = listOf("LAB_FORCE_PLATE_V1"),
            minimumAttempts = 3,
            maximumAttempts = 3,
            restPeriodSeconds = 300,
            executionWindowSeconds = 3600,
            validityWindowDays = 60,
            safetyRequirements = listOf("CERTIFIED_LABORATORY"),
            scoringMethod = TrialScoringMethod.BEST_ATTEMPT,
            thresholdValue = null,
            thresholdUnit = "N",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_17 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-17-V1",
            classId = ClassCatalog.CLASS_17,
            version = "1.0.0",
            name = "Prova de Potência e Absorção Elástica",
            description = "Salto em profundidade (Drop Jump) com índice de força reativa (RSI).",
            category = TrialCategory.BIOMECHANICAL,
            requiredEvidenceTypes = listOf("DROP_JUMP_FORCE_TIME", "CONTACT_TIME_SERIES"),
            protocolId = "PROT-TRIAL-DROP-JUMP-01",
            allowedDevices = listOf("LAB_FORCE_PLATE_V1"),
            minimumAttempts = 3,
            maximumAttempts = 5,
            restPeriodSeconds = 180,
            executionWindowSeconds = 3600,
            validityWindowDays = 60,
            safetyRequirements = listOf("SAFETY_BOX_CERTIFIED"),
            scoringMethod = TrialScoringMethod.BEST_ATTEMPT,
            thresholdValue = null,
            thresholdUnit = "RSI_INDEX",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_18 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-18-V1",
            classId = ClassCatalog.CLASS_18,
            version = "1.0.0",
            name = "Prova de Rendimento de Alta Intensidade",
            description = "Teste supramáximo de produção de trabalho com monitoramento de lactato e potência.",
            category = TrialCategory.CARDIORESPIRATORY,
            requiredEvidenceTypes = listOf("ERGOMETER_POWER_ARRAY", "BLOOD_LACTATE_ASSESSMENT"),
            protocolId = "PROT-TRIAL-WINGATE-30S",
            allowedDevices = listOf("CALIBRATED_CYCLE_ERGOMETER_V1"),
            minimumAttempts = 1,
            maximumAttempts = 1,
            restPeriodSeconds = 1800,
            executionWindowSeconds = 7200,
            validityWindowDays = 60,
            safetyRequirements = listOf("CARDIOLOGIST_CLEARANCE", "DEFIBRILLATOR_ACCESSIBLE"),
            scoringMethod = TrialScoringMethod.BEST_ATTEMPT,
            thresholdValue = null,
            thresholdUnit = "W/kg_PEAK",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_19 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-19-V1",
            classId = ClassCatalog.CLASS_19,
            version = "1.0.0",
            name = "Prova de Integração Neuromuscular Multi-Plano",
            description = "Mudança de direção e desaceleração controlada em pista sensorizada.",
            category = TrialCategory.REACTION_AGILITY,
            requiredEvidenceTypes = listOf("DECELERATION_OPTICAL_ARRAY", "FORCE_VECTOR_ANALYSIS"),
            protocolId = "PROT-TRIAL-COD-505-SENS",
            allowedDevices = listOf("LAB_FORCE_PLATE_V1", "OPTICAL_TIMING_GATES_V1"),
            minimumAttempts = 2,
            maximumAttempts = 3,
            restPeriodSeconds = 240,
            executionWindowSeconds = 3600,
            validityWindowDays = 60,
            safetyRequirements = listOf("NON_SLIP_SURFACE_AUDITED"),
            scoringMethod = TrialScoringMethod.BEST_ATTEMPT,
            thresholdValue = null,
            thresholdUnit = "SECONDS",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_20 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-20-V1",
            classId = ClassCatalog.CLASS_20,
            version = "1.0.0",
            name = "Prova Magna de Potência Contínua",
            description = "Bateria de testes em esteira de alta velocidade com calorimetria indireta direta.",
            category = TrialCategory.CARDIORESPIRATORY,
            requiredEvidenceTypes = listOf("SPIROMETRY_BREATH_BY_BREATH", "FORCE_TREADMILL_TELEMETRY"),
            protocolId = "PROT-TRIAL-VO2-MAX-RAMP",
            allowedDevices = listOf("METABOLIC_CART_GOLD_STANDARD", "INSTRUMENTED_TREADMILL_V1"),
            minimumAttempts = 1,
            maximumAttempts = 1,
            restPeriodSeconds = 3600,
            executionWindowSeconds = 7200,
            validityWindowDays = 45,
            safetyRequirements = listOf("CARDIAC_MONITORING_12_LEAD", "MD_SUPERVISED"),
            scoringMethod = TrialScoringMethod.BEST_ATTEMPT,
            thresholdValue = null,
            thresholdUnit = "mL/kg/min",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_21 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-21-V1",
            classId = ClassCatalog.CLASS_21,
            version = "1.0.0",
            name = "Prova de Resiliência Neuromuscular Máxima",
            description = "Protocolo de fadiga induzida com aferição de contração voluntária máxima (MVC) e estimulação magnética.",
            category = TrialCategory.NEUROMUSCULAR,
            requiredEvidenceTypes = listOf("TWITCH_INTERPOLATION_EMG", "ISOKINETIC_TORQUE_ARRAY"),
            protocolId = "PROT-TRIAL-TMS-TWITCH-01",
            allowedDevices = listOf("DUAL_AXIS_ISOKINETIC_V1", "TMS_SURFACE_EMG_V1"),
            minimumAttempts = 2,
            maximumAttempts = 2,
            restPeriodSeconds = 600,
            executionWindowSeconds = 5400,
            validityWindowDays = 30,
            safetyRequirements = listOf("NEUROPHYSIOLOGY_LAB_ACCREDITED"),
            scoringMethod = TrialScoringMethod.BEST_ATTEMPT,
            thresholdValue = null,
            thresholdUnit = "PERCENT_CENTRAL_ACTIVATION",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        ),
        ClassCatalog.CLASS_22 to TrialPolicy(
            trialPolicyId = "TRIAL-POL-CLASS-22-V1",
            classId = ClassCatalog.CLASS_22,
            version = "1.0.0",
            name = "Prova Suprema de Desempenho Humano Homologado",
            description = "Bateria multidimensional sob estresse extremo em ambiente fisiológico controlado de alto padrão.",
            category = TrialCategory.MAXIMUM_STRENGTH,
            requiredEvidenceTypes = listOf("MULTI_AXIS_IMTP_SERIES", "SPIROMETRY_BREATH_BY_BREATH", "TWITCH_INTERPOLATION_EMG"),
            protocolId = "PROT-TRIAL-SUPREME-OLYMPIC-01",
            allowedDevices = listOf("LAB_FORCE_PLATE_V1", "METABOLIC_CART_GOLD_STANDARD", "TMS_SURFACE_EMG_V1"),
            minimumAttempts = 3,
            maximumAttempts = 3,
            restPeriodSeconds = 900,
            executionWindowSeconds = 14400,
            validityWindowDays = 30,
            safetyRequirements = listOf("FULL_MEDICAL_COMMITTEE_PRESENT"),
            scoringMethod = TrialScoringMethod.ALL_QUALIFIED,
            thresholdValue = null,
            thresholdUnit = "COMPOSITE_SCORE",
            methodologyStatus = "PENDING_VALIDATION",
            status = "ACTIVE"
        )
    )

    fun getPolicyForClass(classId: String): TrialPolicy? =
        policies[classId] ?: policies.entries.find { it.key.startsWith(classId) || classId.startsWith(it.key) }?.value

    fun getPolicyById(policyId: String): TrialPolicy? =
        policies.values.find { it.trialPolicyId == policyId }

    fun getAllPolicies(): List<TrialPolicy> = policies.values.toList()

    fun isTrialRequiredForClass(classId: String): Boolean = getPolicyForClass(classId) != null
}
